server:
  context-path: /bi-message-svc/v1
  port: 8080
  error.whitelabel.enabled: false

application:
  api:
    id: bi-message-svc
    version: v1

endpoints:
  info:
    enabled: true

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

microservice:
  oauth2:
    enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://info4c_prtfl_dev:phaegeogeethaiza@localhost/info4c_prtfl_dev
      collection-name: Info4C_PEP_Desk_raw_Entry.xml
  datasource:
      url: jdbc:mariadb://localhost:3306/aml_prtfl_s_dev
      driver-class-name: org.mariadb.jdbc.Driver
      username: aml_prtfl_s_dev
      password: iemeTuopa3Ee
      platform: mysql
      separator: ;

